version: '3.7'

networks:
  inception:
    driver: bridge

services:
  mariadb:
    environment:
      - MARIADB_ROOT_PASSWORD
      - MARIADB_DATABASE
      - MARIADB_USER
      - MARIADB_USER_PASSWORD
      - MARIADB_PORT
      - MARIADB_HOST
      - WORDPRESS_DB_NAME
    build: requirements/mariadb
    image: mariadb:mine
    container_name: mariadb
    init: true
    restart: on-failure
    expose:
      - 3306
    networks:
      - inception
    healthcheck: # https://medium.com/geekculture/how-to-successfully-implement-a-healthcheck-in-docker-compose-efced60bc08e
      test: [ "CMD-SHELL", "mysql --user=root --password=${MARIADB_ROOT_PASSWORD} --execute \"SELECT User, Host FROM mysql.user WHERE User='${MARIADB_USER}' AND Host='%'; FLUSH PRIVILEGES;\" ${WORDPRESS_DB_NAME}" ]
      start_period: 1m
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - mariadb_vol:/var/lib/mysql

  nginx:
    environment:
      - DOMAIN_NAME
      - WORDPRESS_PORT
    build: requirements/nginx
    image: nginx:mine
    container_name: nginx
    init: true
    restart: on-failure
    networks:
      - inception
    ports:
      - '443:443'
    depends_on:
      wordpress:
        condition: service_healthy
    volumes:
      - wordpress_vol:/var/www/html/
      - nginx_logs_vol:/var/log/nginx
    
  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    image: wordpress:mine
    environment:
      - WORDPRESS_URL
      - WORDPRESS_TITLE
      - WORDPRESS_USER_NAME
      - WORDPRESS_USER_PASSWORD
      - WORDPRESS_USER_EMAIL
      - WORDPRESS_ADMIN_NAME
      - WORDPRESS_ADMIN_PASSWORD
      - WORDPRESS_ADMIN_EMAIL
      - WORDPRESS_DB_NAME
      - WORDPRESS_PORT
      - MARIADB_ROOT_PASSWORD
      - MARIADB_DATABASE
      - MARIADB_USER
      - MARIADB_USER_PASSWORD
      - MARIADB_PORT
      - MARIADB_HOST
    init: true
    restart: on-failure
    expose:
      - 9000
    networks:
      - inception
    healthcheck:
      test: ["CMD-SHELL", "if [ ! -f /usr/local/bin/.docker-entrypoint-finished ]; then exit 1; fi"]
      start_period: 1m
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - wordpress_vol:/var/www/html/

volumes:
  mariadb_vol:
    driver: local
    driver_opts:
      type: none
      device: /home/${LOGIN}/data/mariadb_volume
      o: bind
  wordpress_vol:
    driver: local
    driver_opts:
      type: none
      device: /home/${LOGIN}/data/wordpress_volume
      o: bind
  nginx_logs_vol:
    driver: local
    driver_opts:
      type: none
      device: /home/${LOGIN}/data/logs/nginx
      o: bind